### ISSUE TITLE
How I can use it with Github Pages?

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/jekyll-bits#17]
![image](https://user-images.githubusercontent.com/5731084/32798085-431aeb12-c9a6-11e7-8bbc-51bf3016731e.png)
Github can not build site with tag `jb_picture_body`:

Your site is having problems building: The tag jb_picture_body on line 3 in _posts/... is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey you can't use it with GitHub Pages, because of: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

**Comment by nikialeksey** [comment]
Oh, yes. Thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/jekyll-bits#17`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/jekyll-bits#17` is not in scope.
